/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.GrnModel;
import org.apache.log4j.Logger;

/**
 *
 * @author EZIO AUDITORY
 */
public class GrnManager extends javax.swing.JFrame {

    /**
     * Creates new form GrnManager
     */
    private GrnModel grnModel;
    private LoadSupplierDialog loadSupplierDialog;
    private LoadProductDialog loadProductDialog;
    static Logger logger = Logger.getLogger(GrnManager.class.getName());

    DefaultTableModel grnTableModel;
    DefaultTableModel grnHistoryTableModel;

    int supplierNo;
    int selectedRow;

    public GrnManager() {
        initComponents();
        logger.debug("Access to GrnManager.java");

        grnTableModel = (DefaultTableModel) grnTable.getModel();
        grnHistoryTableModel = (DefaultTableModel) grnHistoryTable.getModel();

        grnModel = new GrnModel();
        loadSupplierDialog = new LoadSupplierDialog(this, rootPaneCheckingEnabled);
        loadProductDialog = new LoadProductDialog(this, rootPaneCheckingEnabled);

        grnNoLoad();
        loadGrnHistoryTable("");

        grnDateChooser.setDate(new java.util.Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        grnNoField = new javax.swing.JTextField();
        grnDateChooser = new com.toedter.calendar.JDateChooser();
        supplierNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grnTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        totalDiscountField = new javax.swing.JTextField();
        totalAmountField = new javax.swing.JTextField();
        netAmountField = new javax.swing.JTextField();
        totalVatField = new javax.swing.JTextField();
        itemCountField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        deleteRowButton = new javax.swing.JButton();
        saveGrnButton = new javax.swing.JButton();
        newGrnButton = new javax.swing.JButton();
        GrnButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        unitSellPriceField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        qtyField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        unitNameField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        unitBuyPriceField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        vatField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        addRowButton = new javax.swing.JButton();
        updateRowButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        productNoField = new javax.swing.JTextField();
        clearFiledsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        keywordField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        grnHistoryTable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        grnButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grn Manager");
        setResizable(false);

        grnNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                grnNoFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grnNoFieldKeyReleased(evt);
            }
        });

        grnDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                grnDateChooserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grnDateChooserKeyReleased(evt);
            }
        });

        supplierNameField.setText("Select Supplier");
        supplierNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierNameFieldMouseClicked(evt);
            }
        });
        supplierNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supplierNameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierNameFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("GRN No");

        jLabel2.setText("Supplier");

        jLabel3.setText("GRN Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(grnNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grnDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(supplierNameField))
                .addGap(654, 654, 654))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(grnNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(grnDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        grnTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        grnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pno", "Product", "Unit Sell Price", "Qty", "Unit", "Unit Buy Price", "Discount", "VAT", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grnTable.setDragEnabled(true);
        grnTable.setRowHeight(30);
        grnTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        grnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grnTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grnTable);
        if (grnTable.getColumnModel().getColumnCount() > 0) {
            grnTable.getColumnModel().getColumn(0).setMinWidth(60);
            grnTable.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        totalDiscountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalDiscountField.setText("0.0");
        totalDiscountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalDiscountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalDiscountFieldKeyReleased(evt);
            }
        });

        totalAmountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalAmountField.setText("0.0");
        totalAmountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalAmountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalAmountFieldKeyReleased(evt);
            }
        });

        netAmountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        netAmountField.setText("0.0");
        netAmountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                netAmountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                netAmountFieldKeyReleased(evt);
            }
        });

        totalVatField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalVatField.setText("0.0");
        totalVatField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalVatFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalVatFieldKeyReleased(evt);
            }
        });

        itemCountField.setText("0");
        itemCountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemCountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemCountFieldKeyReleased(evt);
            }
        });

        jLabel4.setText("Item Count");

        jLabel5.setText("Discount");

        jLabel6.setText("VAT");

        jLabel7.setText("Total Amount");

        jLabel8.setText("Net Amount");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalVatField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDiscountField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netAmountField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(itemCountField))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCountField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalDiscountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalVatField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteRowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteRowButton.setText("Delete Row");
        deleteRowButton.setEnabled(false);
        deleteRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowButtonActionPerformed(evt);
            }
        });

        saveGrnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveGrnButton.setText("Save GRN");
        saveGrnButton.setEnabled(false);
        saveGrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGrnButtonActionPerformed(evt);
            }
        });

        newGrnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newGrnButton.setText("New");
        newGrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGrnButtonActionPerformed(evt);
            }
        });

        GrnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GrnButton.setText("GRN");
        GrnButton.setEnabled(false);
        GrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(deleteRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel9.setText("Product");

        productNameField.setText("Select Product");
        productNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productNameFieldMouseClicked(evt);
            }
        });
        productNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productNameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productNameFieldKeyReleased(evt);
            }
        });

        jLabel10.setText("Unit Sell Price");

        unitSellPriceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitSellPriceField.setText("0.0");
        unitSellPriceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unitSellPriceFieldFocusLost(evt);
            }
        });
        unitSellPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitSellPriceFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitSellPriceFieldKeyReleased(evt);
            }
        });

        jLabel11.setText("Qty");

        qtyField.setText("0.0");
        qtyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyFieldFocusLost(evt);
            }
        });
        qtyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyFieldKeyReleased(evt);
            }
        });

        jLabel12.setText("Unit");

        unitNameField.setText("Number");
        unitNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitNameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitNameFieldKeyReleased(evt);
            }
        });

        jLabel13.setText("Unit Buy Price");

        unitBuyPriceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unitBuyPriceField.setText("0.0");
        unitBuyPriceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unitBuyPriceFieldFocusLost(evt);
            }
        });
        unitBuyPriceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitBuyPriceFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitBuyPriceFieldKeyReleased(evt);
            }
        });

        jLabel14.setText("Discount");

        discountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discountField.setText("0.0");
        discountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discountFieldFocusLost(evt);
            }
        });
        discountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                discountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountFieldKeyReleased(evt);
            }
        });

        jLabel15.setText("VAT");

        vatField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vatField.setText("0.0");
        vatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vatFieldFocusLost(evt);
            }
        });
        vatField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vatFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vatFieldKeyReleased(evt);
            }
        });

        jLabel16.setText("Amount");

        amountField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amountField.setText("0.0");
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountFieldKeyReleased(evt);
            }
        });

        addRowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addRowButton.setText("Add Row");
        addRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowButtonActionPerformed(evt);
            }
        });

        updateRowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateRowButton.setText("Update Row");
        updateRowButton.setEnabled(false);
        updateRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRowButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("No");

        productNoField.setText("0");
        productNoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productNoFieldMouseClicked(evt);
            }
        });
        productNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productNoFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productNoFieldKeyReleased(evt);
            }
        });

        clearFiledsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearFiledsButton.setText("Clear Fields");
        clearFiledsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFiledsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitSellPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitBuyPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearFiledsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vatField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(productNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(unitSellPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(qtyField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(unitNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(unitBuyPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(discountField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(vatField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(productNoField)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearFiledsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create GRN", jPanel1);

        keywordField.setForeground(new java.awt.Color(153, 153, 153));
        keywordField.setText("Search");
        keywordField.setToolTipText("Search");
        keywordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keywordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keywordFieldFocusLost(evt);
            }
        });
        keywordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordFieldKeyReleased(evt);
            }
        });

        grnHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grn No", "GRN Date", "Supplier", "Item Count", "Total Discount", "Total Vat", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnHistoryTable.setRowHeight(25);
        jScrollPane3.setViewportView(grnHistoryTable);
        if (grnHistoryTable.getColumnModel().getColumnCount() > 0) {
            grnHistoryTable.getColumnModel().getColumn(0).setMinWidth(100);
            grnHistoryTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        grnButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grnButton1.setText("GRN");
        grnButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1831, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(grnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GRN History", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supplierNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierNameFieldMouseClicked
        // TODO add your handling code here:
        loadSupplierDialog.setVisible(true);

        Object[] supplierData = loadSupplierDialog.getSupplierData();
        supplierNo = (int) supplierData[0];
        logger.debug("Select supplier");
        supplierNameField.setText((String) supplierData[1]);
        logger.debug("Set selected supplier data to text fields");
    }//GEN-LAST:event_supplierNameFieldMouseClicked

    private void productNoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNoFieldMouseClicked
        // TODO add your handling code here:
        loadProductDialog.setVisible(true);

        Object[] productData = loadProductDialog.getProductData();

        String productNoo = new String(productData[0] + "");
        String productName = (String) productData[1];
        String productUnitName = (String) productData[2];
        logger.debug("Select product");
        productNoField.setText(productNoo);
        productNameField.setText(productName);
        unitNameField.setText(productUnitName);
        logger.debug("Set selected product data to text fields");
        calculateValues();
    }//GEN-LAST:event_productNoFieldMouseClicked

    private void productNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productNameFieldMouseClicked
        // TODO add your handling code here:
        loadProductDialog.setVisible(true);

        Object[] productData = loadProductDialog.getProductData();

        String productNoo = new String(productData[0] + "");
        String productName = (String) productData[1];
        String productUnitName = (String) productData[2];
        logger.debug("Select product");
        productNoField.setText(productNoo);
        productNameField.setText(productName);
        unitNameField.setText(productUnitName);
        logger.debug("Set selected product data to text fields");
        calculateValues();
    }//GEN-LAST:event_productNameFieldMouseClicked

    private void addRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonActionPerformed
        // TODO add your handling code here:
        logger.debug("Add row");
        String productNo = productNoField.getText();
        String productName = productNameField.getText();
        String unitSellPrice = unitSellPriceField.getText();
        String qty = qtyField.getText();
        String unitName = unitNameField.getText();
        String unitBuyPrice = unitBuyPriceField.getText();
        String discount = discountField.getText();
        String vat = vatField.getText();
        String amount = amountField.getText();

        String PATTERN = "^[0]{0,100}[.][0]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m1 = p.matcher(unitSellPrice);
        Matcher m2 = p.matcher(qty);
        Matcher m3 = p.matcher(unitBuyPrice);

        logger.debug("Check validations");
        if (supplierNo == 0 || supplierNameField.equals("Select Supplier")) {
            logger.error("Supplier not selected");
            loadSupplierDialog.setVisible(true);
            Object[] supplierData = loadSupplierDialog.getSupplierData();
            supplierNo = (int) supplierData[0];
            logger.debug("Select supplier");
            supplierNameField.setText((String) supplierData[1]);
            logger.debug("Set selected supplier data to text fields");
        } else if (productNo.equals("0") || productName.equals("Select Product")) {
            logger.error("Product not selected");
            loadProductDialog.setVisible(true);

            Object[] productData = loadProductDialog.getProductData();

            String productNoo = new String(productData[0] + "");
            String productNameSet = (String) productData[1];
            String productUnitName = (String) productData[2];
            logger.debug("Select product");
            productNoField.setText(productNoo);
            productNameField.setText(productNameSet);
            unitNameField.setText(productUnitName);
            logger.debug("Set selected product data to text fields");

        } else if (m1.matches()) {
            unitSellPriceField.requestFocus(true);
            logger.error("unit sell price not entered");
        } else if (m2.matches()) {
            qtyField.requestFocus(true);
            logger.error("qty not entered");
        } else if (m3.matches()) {
            unitBuyPriceField.requestFocus(true);
            logger.error("unit buy price not entered");
        } else {
            grnTableModel.addRow(new Object[]{Integer.parseInt(productNo), productName, Double.parseDouble(unitSellPrice), Double.parseDouble(qty), unitName,
                Double.parseDouble(unitBuyPrice), Double.parseDouble(discount), Double.parseDouble(vat), Double.parseDouble(amount)});
            logger.debug("Add row successful");
            saveGrnButton.setEnabled(true);
            itemCountField.setText(String.valueOf(grnTableModel.getRowCount()));
            calculateValues();
            clearFields();
        }
        calculateValues();
    }//GEN-LAST:event_addRowButtonActionPerformed

    private void updateRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRowButtonActionPerformed
        // TODO add your handling code here:
        logger.debug("Update selected row");
        String productNo = productNoField.getText();
        String productName = productNameField.getText();
        String unitSellPrice = unitSellPriceField.getText();
        String qty = qtyField.getText();
        String unitName = unitNameField.getText();
        String unitBuyPrice = unitBuyPriceField.getText();
        String discount = discountField.getText();
        String vat = vatField.getText();
        String amount = amountField.getText();

        String PATTERN = "^[0]{0,100}[.][0]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m1 = p.matcher(unitSellPrice);
        Matcher m2 = p.matcher(qty);
        Matcher m3 = p.matcher(unitBuyPrice);

        logger.debug("Check validations");
        if (m1.matches()) {
            unitSellPriceField.requestFocus(true);
            logger.error("unit sell price not entered");
        } else if (m2.matches()) {
            qtyField.requestFocus(true);
            logger.error("qty not entered");
        } else if (m3.matches()) {
            unitBuyPriceField.requestFocus(true);
            logger.error("unit buy price not entered");
        } else {
            Object[] addrow = new Object[]{Integer.parseInt(productNo), productName, Double.parseDouble(unitSellPrice), Double.parseDouble(qty), unitName,
                Double.parseDouble(unitBuyPrice), Double.parseDouble(discount), Double.parseDouble(vat), Double.parseDouble(amount)};

            grnTableModel.setValueAt(addrow[0], selectedRow, 0);
            grnTableModel.setValueAt(addrow[1], selectedRow, 1);
            grnTableModel.setValueAt(addrow[2], selectedRow, 2);
            grnTableModel.setValueAt(addrow[3], selectedRow, 3);
            grnTableModel.setValueAt(addrow[4], selectedRow, 4);
            grnTableModel.setValueAt(addrow[5], selectedRow, 5);
            grnTableModel.setValueAt(addrow[6], selectedRow, 6);
            grnTableModel.setValueAt(addrow[7], selectedRow, 7);
            grnTableModel.setValueAt(addrow[8], selectedRow, 8);
            logger.debug("Update selected row successful");
            saveGrnButton.setEnabled(true);
            itemCountField.setText(String.valueOf(grnTableModel.getRowCount()));
            calculateValues();
            clearFields();
        }
        calculateValues();
    }//GEN-LAST:event_updateRowButtonActionPerformed

    private void deleteRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowButtonActionPerformed
        // TODO add your handling code here:
        logger.debug("Delete selected row");
        int rowCount = grnTable.getRowCount();
        int selectedRow = grnTable.getSelectedRow();
        int selectedRowCount = grnTable.getSelectedRowCount();

        if (selectedRowCount == 1) {
            grnTableModel.removeRow(selectedRow);
            logger.debug("Delete selected row successful");
            clearFields();
            if (rowCount == 1) {
                saveGrnButton.setEnabled(false);
            }
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Please Select Any Single Row !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            logger.error("Error: Please Select Any Single Row !");
        }
        calculateValues();
    }//GEN-LAST:event_deleteRowButtonActionPerformed

    private void saveGrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGrnButtonActionPerformed
        // TODO add your handling code here:
        calculateValues();
        int rowCount = grnTableModel.getRowCount();

        String grnNo = grnNoField.getText();
        Date grnDate = grnDateChooser.getDate();
        //supplierNo in hear
        String itemCount = itemCountField.getText();
        String totalDiscount = totalDiscountField.getText();
        String totalVat = totalVatField.getText();
        String totalAmount = totalAmountField.getText();

        logger.debug("Save grn");
        String grnResult = grnModel.saveGrn(grnNo, grnDate, supplierNo, itemCount, totalDiscount, totalVat, totalAmount);

        String grnItemResult = null;
        String stockResult = null;
        for (int i = 0; i < rowCount; i++) {
            int productNo = (int) grnTableModel.getValueAt(i, 0);
            double unitSellPrice = (double) grnTableModel.getValueAt(i, 2);
            double qty = (double) grnTableModel.getValueAt(i, 3);
            double unitBuyPrice = (double) grnTableModel.getValueAt(i, 5);
            double discount = (double) grnTableModel.getValueAt(i, 6);
            double vat = (double) grnTableModel.getValueAt(i, 7);
            double amount = (double) grnTableModel.getValueAt(i, 8);

            logger.debug("Save grn item");
            grnItemResult = grnModel.saveGrnItem(productNo, unitSellPrice, qty, unitBuyPrice, discount, vat, amount, grnNo);
            logger.debug("Update stock");
            stockResult = grnModel.updateStock(grnDate, productNo, qty, unitSellPrice);
        }

        if (grnResult.equals("Save Successful") && grnItemResult.equals("Save Successful") && stockResult.equals("Save Successful")) {
            JOptionPane.showConfirmDialog(rootPane, "Save Successful", "Message", -1, 1);
            GrnButton.setEnabled(true);
            clearFields();
            addRowButton.setEnabled(false);
            updateRowButton.setEnabled(false);
            clearFiledsButton.setEnabled(false);
            grnTable.setEnabled(false);
            grnTable.clearSelection();
            deleteRowButton.setEnabled(false);
            saveGrnButton.setEnabled(false);
            loadGrnHistoryTable("");
            logger.debug("Message: Save Successful");
        } else {
            JOptionPane.showConfirmDialog(rootPane, "Save Error !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            logger.error("Error: Save Error !");
        }
    }//GEN-LAST:event_saveGrnButtonActionPerformed

    private void grnTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnTableMouseClicked
        // TODO add your handling code here:
        selectedRow = grnTable.getSelectedRow();
        try {
            productNoField.setText(new String(grnTableModel.getValueAt(selectedRow, 0) + ""));
            productNameField.setText((String) grnTableModel.getValueAt(selectedRow, 1));
            unitSellPriceField.setText(new String(grnTableModel.getValueAt(selectedRow, 2) + ""));
            qtyField.setText(new String(grnTableModel.getValueAt(selectedRow, 3) + ""));
            unitNameField.setText((String) grnTableModel.getValueAt(selectedRow, 4));
            unitBuyPriceField.setText(new String(grnTableModel.getValueAt(selectedRow, 5) + ""));
            discountField.setText(new String(grnTableModel.getValueAt(selectedRow, 6) + ""));
            vatField.setText(new String(grnTableModel.getValueAt(selectedRow, 7) + ""));
            amountField.setText(new String(grnTableModel.getValueAt(selectedRow, 8) + ""));
            logger.debug("Load selected row data to relevant text fields");
            
            addRowButton.setEnabled(false);
            updateRowButton.setEnabled(true);
            deleteRowButton.setEnabled(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
            logger.error("Exception: " + e.getMessage());
        }

    }//GEN-LAST:event_grnTableMouseClicked

    private void clearFiledsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFiledsButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearFiledsButtonActionPerformed

    private void newGrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGrnButtonActionPerformed
        // TODO add your handling code here:
        int rowCount = grnTableModel.getRowCount();

        grnNoLoad();
        supplierNo = 0;
        supplierNameField.setText("Select Supplier");
        grnDateChooser.setDate(new java.util.Date());

        clearFields();
        clearFiledsButton.setEnabled(true);

        for (int i = rowCount - 1; i >= 0; i--) {
            grnTableModel.removeRow(i);
        }

        grnTable.setEnabled(true);
        saveGrnButton.setEnabled(false);
        GrnButton.setEnabled(false);

        itemCountField.setText("0");
        totalDiscountField.setText("0.0");
        totalVatField.setText("0.0");
        totalAmountField.setText("0.0");
        netAmountField.setText("0.0");

        logger.debug("Open new grn");
    }//GEN-LAST:event_newGrnButtonActionPerformed

    private void GrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrnButtonActionPerformed
        // TODO add your handling code here:
        int grnNo = Integer.parseInt(grnNoField.getText());
        new GenerateGrnDialog(this, true, grnNo).setVisible(true);
    }//GEN-LAST:event_GrnButtonActionPerformed


    private void grnNoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnNoFieldKeyPressed
        // TODO add your handling code here:
        grnNoField.setEditable(false);
    }//GEN-LAST:event_grnNoFieldKeyPressed

    private void grnDateChooserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnDateChooserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_grnDateChooserKeyPressed

    private void supplierNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameFieldKeyPressed
        // TODO add your handling code here:
        supplierNameField.setEditable(false);
    }//GEN-LAST:event_supplierNameFieldKeyPressed

    private void productNoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNoFieldKeyPressed
        // TODO add your handling code here:
        productNoField.setEditable(false);
    }//GEN-LAST:event_productNoFieldKeyPressed

    private void productNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameFieldKeyPressed
        // TODO add your handling code here:
        productNameField.setEditable(false);
    }//GEN-LAST:event_productNameFieldKeyPressed

    private void unitSellPriceFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitSellPriceFieldKeyPressed
        // TODO add your handling code here:
        String unitSellPrice = unitSellPriceField.getText();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') {
            unitSellPriceField.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                unitSellPriceField.setEditable(true);
            } else {
                unitSellPriceField.setEditable(false);
            }
        }
    }//GEN-LAST:event_unitSellPriceFieldKeyPressed

    private void qtyFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyFieldKeyPressed
        // TODO add your handling code here:
        String qty = qtyField.getText();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') {
            qtyField.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                qtyField.setEditable(true);
            } else {
                qtyField.setEditable(false);
            }
        }
    }//GEN-LAST:event_qtyFieldKeyPressed

    private void unitNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitNameFieldKeyPressed
        // TODO add your handling code here:
        unitNameField.setEditable(false);
    }//GEN-LAST:event_unitNameFieldKeyPressed

    private void unitBuyPriceFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitBuyPriceFieldKeyPressed
        // TODO add your handling code here:
        String unitBuyPrice = unitBuyPriceField.getText();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') {
            unitBuyPriceField.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                unitBuyPriceField.setEditable(true);
            } else {
                unitBuyPriceField.setEditable(false);
            }
        }
    }//GEN-LAST:event_unitBuyPriceFieldKeyPressed

    private void discountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountFieldKeyPressed
        // TODO add your handling code here:
        String discount = discountField.getText();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') {
            discountField.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                discountField.setEditable(true);
            } else {
                discountField.setEditable(false);
            }
        }
    }//GEN-LAST:event_discountFieldKeyPressed

    private void vatFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vatFieldKeyPressed
        // TODO add your handling code here:
        String vat = vatField.getText();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == '.') {
            vatField.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                vatField.setEditable(true);
            } else {
                vatField.setEditable(false);
            }
        }
    }//GEN-LAST:event_vatFieldKeyPressed

    private void amountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyPressed
        // TODO add your handling code here:
        amountField.setEditable(false);
    }//GEN-LAST:event_amountFieldKeyPressed

    private void itemCountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCountFieldKeyPressed
        // TODO add your handling code here:
        itemCountField.setEditable(false);
    }//GEN-LAST:event_itemCountFieldKeyPressed

    private void totalDiscountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalDiscountFieldKeyPressed
        // TODO add your handling code here:
        totalDiscountField.setEditable(false);
    }//GEN-LAST:event_totalDiscountFieldKeyPressed

    private void totalVatFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalVatFieldKeyPressed
        // TODO add your handling code here:
        totalVatField.setEditable(false);
    }//GEN-LAST:event_totalVatFieldKeyPressed

    private void totalAmountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalAmountFieldKeyPressed
        // TODO add your handling code here:
        totalAmountField.setEditable(false);
    }//GEN-LAST:event_totalAmountFieldKeyPressed

    private void netAmountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netAmountFieldKeyPressed
        // TODO add your handling code here:
        netAmountField.setEditable(false);
    }//GEN-LAST:event_netAmountFieldKeyPressed

    private void grnNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnNoFieldKeyReleased
        // TODO add your handling code here:
        grnNoField.setEditable(true);
    }//GEN-LAST:event_grnNoFieldKeyReleased

    private void grnDateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnDateChooserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_grnDateChooserKeyReleased

    private void supplierNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameFieldKeyReleased
        // TODO add your handling code here:
        supplierNameField.setEditable(true);
    }//GEN-LAST:event_supplierNameFieldKeyReleased

    private void productNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNoFieldKeyReleased
        // TODO add your handling code here:
        productNoField.setEditable(true);
    }//GEN-LAST:event_productNoFieldKeyReleased

    private void productNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameFieldKeyReleased
        // TODO add your handling code here:
        productNameField.setEditable(true);
    }//GEN-LAST:event_productNameFieldKeyReleased

    private void unitSellPriceFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitSellPriceFieldKeyReleased
        // TODO add your handling code here:
        unitSellPriceField.setEditable(true);
    }//GEN-LAST:event_unitSellPriceFieldKeyReleased

    private void qtyFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyFieldKeyReleased
        // TODO add your handling code here:
        qtyField.setEditable(true);
        calculateValues();
    }//GEN-LAST:event_qtyFieldKeyReleased

    private void unitNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitNameFieldKeyReleased
        // TODO add your handling code here:
        unitNameField.setEditable(true);
    }//GEN-LAST:event_unitNameFieldKeyReleased

    private void unitBuyPriceFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitBuyPriceFieldKeyReleased
        // TODO add your handling code here:
        unitBuyPriceField.setEditable(true);
        calculateValues();
    }//GEN-LAST:event_unitBuyPriceFieldKeyReleased

    private void discountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountFieldKeyReleased
        // TODO add your handling code here:
        discountField.setEditable(true);
        calculateValues();
    }//GEN-LAST:event_discountFieldKeyReleased

    private void vatFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vatFieldKeyReleased
        // TODO add your handling code here:
        vatField.setEditable(true);
        calculateValues();
    }//GEN-LAST:event_vatFieldKeyReleased

    private void amountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyReleased
        // TODO add your handling code here:
        amountField.setEditable(true);
    }//GEN-LAST:event_amountFieldKeyReleased

    private void itemCountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCountFieldKeyReleased
        // TODO add your handling code here:
        itemCountField.setEditable(true);
    }//GEN-LAST:event_itemCountFieldKeyReleased

    private void totalDiscountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalDiscountFieldKeyReleased
        // TODO add your handling code here:
        totalDiscountField.setEditable(true);
    }//GEN-LAST:event_totalDiscountFieldKeyReleased

    private void totalVatFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalVatFieldKeyReleased
        // TODO add your handling code here:
        totalVatField.setEditable(true);
    }//GEN-LAST:event_totalVatFieldKeyReleased

    private void totalAmountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalAmountFieldKeyReleased
        // TODO add your handling code here:
        totalAmountField.setEditable(true);
    }//GEN-LAST:event_totalAmountFieldKeyReleased

    private void netAmountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netAmountFieldKeyReleased
        // TODO add your handling code here:
        netAmountField.setEditable(true);
    }//GEN-LAST:event_netAmountFieldKeyReleased

    private void unitSellPriceFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unitSellPriceFieldFocusLost
        // TODO add your handling code here:
        String unitSellPrice = unitSellPriceField.getText();
        String PATTERN = "^[0-9]{0,100}[.][0-9]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m = p.matcher(unitSellPrice);
        if (unitSellPrice.equals("")) {
            unitSellPriceField.setText("0.0");
        } else if (!m.matches()) {
            unitSellPriceField.setText(unitSellPrice + ".0");
        }
        calculateValues();
    }//GEN-LAST:event_unitSellPriceFieldFocusLost

    private void qtyFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyFieldFocusLost
        // TODO add your handling code here:
        String qty = qtyField.getText();
        String PATTERN = "^[0-9]{0,100}[.][0-9]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m = p.matcher(qty);
        if (qty.equals("")) {
            qtyField.setText("0.0");
        } else if (!m.matches()) {
            qtyField.setText(qty + ".0");
        }
        calculateValues();
    }//GEN-LAST:event_qtyFieldFocusLost

    private void unitBuyPriceFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unitBuyPriceFieldFocusLost
        // TODO add your handling code here:
        String unitBuyPrice = unitBuyPriceField.getText();
        String PATTERN = "^[0-9]{0,100}[.][0-9]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m = p.matcher(unitBuyPrice);
        if (unitBuyPrice.equals("")) {
            unitBuyPriceField.setText("0.0");
        } else if (!m.matches()) {
            unitBuyPriceField.setText(unitBuyPrice + ".0");
        }
        calculateValues();
    }//GEN-LAST:event_unitBuyPriceFieldFocusLost

    private void discountFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discountFieldFocusLost
        // TODO add your handling code here:
        String discount = discountField.getText();
        String PATTERN = "^[0-9]{0,100}[.][0-9]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m = p.matcher(discount);
        System.out.println(m.matches());
        if (discount.equals("")) {
            discountField.setText("0.0");
        } else if (!m.matches()) {
            discountField.setText(discount + ".0");
        }
        calculateValues();
    }//GEN-LAST:event_discountFieldFocusLost

    private void vatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vatFieldFocusLost
        // TODO add your handling code here:
        String vat = vatField.getText();
        String PATTERN = "^[0-9]{0,100}[.][0-9]{0,100}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher m = p.matcher(vat);
        System.out.println(m.matches());
        if (vat.equals("")) {
            vatField.setText("0.0");
        } else if (!m.matches()) {
            vatField.setText(vat + ".0");
        }
        calculateValues();
    }//GEN-LAST:event_vatFieldFocusLost

    private void keywordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFocusGained
        // TODO add your handling code here:
        if (keywordField.getText().equals("Search")) {
            keywordField.setText("");
            keywordField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keywordFieldFocusGained

    private void keywordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFocusLost
        // TODO add your handling code here:
        if (keywordField.getText().equals("")) {
            keywordField.setText("Search");
            keywordField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_keywordFieldFocusLost

    private void keywordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordFieldKeyReleased
        // TODO add your handling code here:
        String keyword = keywordField.getText();
        logger.debug("Search grn data");
        loadGrnHistoryTable(keyword);
    }//GEN-LAST:event_keywordFieldKeyReleased

    private void grnButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnButton1ActionPerformed
        // TODO add your handling code here:
        int rowCount = grnHistoryTable.getRowCount();
        int selectedRow = grnHistoryTable.getSelectedRow();
        int selectedRowCount = grnHistoryTable.getSelectedRowCount();

        if (selectedRowCount == 1) {
            int grnNo = (int) grnHistoryTableModel.getValueAt(selectedRow, 0);
            new GenerateGrnDialog(this, true, grnNo).setVisible(true);
        } else {
            if (rowCount == 0) {
                JOptionPane.showConfirmDialog(rootPane, "Table is Empty !", "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: Table is Empty !");
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Please Select Any Single Row !", "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: Please Select Any Single Row !");
            }
        }
    }//GEN-LAST:event_grnButton1ActionPerformed

    private void grnNoLoad() {
        int grnNo = grnModel.getGrnNo();
        grnNo++;
        grnNoField.setText(new String(grnNo + ""));
        logger.debug("Set Grn No");
    }

    private void calculateValues() {
        try {
            int rowCount = grnTableModel.getRowCount();

            double productQty = Double.parseDouble(qtyField.getText());
            double productUnitBuyPrice = Double.parseDouble(unitBuyPriceField.getText());
            double productDiscount = Double.parseDouble(discountField.getText());
            double productVat = Double.parseDouble(vatField.getText());
            double productAmount = (productUnitBuyPrice - productDiscount + productVat) * productQty;

            amountField.setText(String.valueOf(productAmount));

            itemCountField.setText(String.valueOf(rowCount));

            double totalDiscount = 0;
            double totalVat = 0;
            double totalAmount = 0;

            for (int i = 0; i < rowCount; i++) {
                double rowQty = (double) grnTableModel.getValueAt(i, 3);

                double rowDiscount = (double) grnTableModel.getValueAt(i, 6);
                totalDiscount += rowDiscount * rowQty;

                double rowVat = (double) grnTableModel.getValueAt(i, 7);
                totalVat += rowVat * rowQty;

                double rowAmount = (double) grnTableModel.getValueAt(i, 8);
                totalAmount += rowAmount;
            }
            totalDiscountField.setText(String.valueOf(totalDiscount));
            totalVatField.setText(String.valueOf(totalVat));
            totalAmountField.setText(String.valueOf(totalAmount));
            netAmountField.setText(String.valueOf(totalAmount));

            logger.debug("Calculate values");
        } catch (NumberFormatException e) {
            logger.error("Exception: " + e.getMessage());
        }
    }

    private void clearFields() {
        productNoField.setText("0");
        productNameField.setText("Select Product");
        unitSellPriceField.setText("0.0");
        qtyField.setText("0.0");
        unitNameField.setText("Number");
        unitBuyPriceField.setText("0.0");
        discountField.setText("0.0");
        vatField.setText("0.0");
        amountField.setText("0.0");

        addRowButton.setEnabled(true);
        updateRowButton.setEnabled(false);
        deleteRowButton.setEnabled(false);

        logger.debug("Clear fields");
    }

    private void loadGrnHistoryTable(String keyword) {
        grnModel.loadGrnHistoryTable(keyword, grnHistoryTableModel);
        logger.debug("Load grn history table");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GrnManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrnManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GrnButton;
    private javax.swing.JButton addRowButton;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton clearFiledsButton;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JButton grnButton1;
    private com.toedter.calendar.JDateChooser grnDateChooser;
    private javax.swing.JTable grnHistoryTable;
    private javax.swing.JTextField grnNoField;
    private javax.swing.JTable grnTable;
    private javax.swing.JTextField itemCountField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keywordField;
    private javax.swing.JTextField netAmountField;
    private javax.swing.JButton newGrnButton;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productNoField;
    private javax.swing.JTextField qtyField;
    private javax.swing.JButton saveGrnButton;
    private javax.swing.JTextField supplierNameField;
    private javax.swing.JTextField totalAmountField;
    private javax.swing.JTextField totalDiscountField;
    private javax.swing.JTextField totalVatField;
    private javax.swing.JTextField unitBuyPriceField;
    private javax.swing.JTextField unitNameField;
    private javax.swing.JTextField unitSellPriceField;
    private javax.swing.JButton updateRowButton;
    private javax.swing.JTextField vatField;
    // End of variables declaration//GEN-END:variables
}
