/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.ComboBoxLoadModel;
import model.SupplierModel;
import org.apache.log4j.Logger;

/**
 *
 * @author EZIO AUDITORY
 */
public class SupplierManager extends javax.swing.JFrame {

    /**
     * Creates new form SupplierManager
     */
    private SupplierModel supplierModel;
    private ComboBoxLoadModel comboBoxLoadModel;
    static Logger logger = Logger.getLogger(SupplierManager.class.getName());

    DefaultTableModel supplierTableModel;

    DefaultComboBoxModel districtComboBoxModel;
    DefaultComboBoxModel provinceComboBoxModel;
    DefaultComboBoxModel companyComboBoxModel;

    public SupplierManager() {
        initComponents();
        logger.debug("Access to SupplierManager.java");

        supplierTableModel = (DefaultTableModel) supplierTable.getModel();

        supplierModel = new SupplierModel();
        comboBoxLoadModel = new ComboBoxLoadModel();

        supplierNoLoad();
        loadSupplierTable("");

        Vector vDistrict = comboBoxLoadModel.districtComboBoxLoad();
        districtComboBoxModel = new DefaultComboBoxModel(vDistrict);
        districtComboBox.setModel(districtComboBoxModel);
        districtComboBox.setSelectedIndex(0);

        Vector vProvince = comboBoxLoadModel.provinceComboBoxLoad();
        provinceComboBoxModel = new DefaultComboBoxModel(vProvince);
        provinceComboBox.setModel(provinceComboBoxModel);
        provinceComboBox.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        supplierNoField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        nicField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        contactNoField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        districtComboBox = new javax.swing.JComboBox<>();
        provinceComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        registerButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        keywordField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supplier Manager");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        supplierNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supplierNoFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierNoFieldKeyReleased(evt);
            }
        });

        contactNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactNoFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNoFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Supplier No");

        jLabel2.setText("Name");

        jLabel3.setText("NIC");

        jLabel4.setText("Email");

        jLabel5.setText("Contact No");

        jLabel6.setText("Address");

        jLabel7.setText("City");

        jLabel8.setText("District");

        jLabel9.setText("Province");

        registerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.setEnabled(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeButton.setText("Remove");
        removeButton.setEnabled(false);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        newButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Gender");

        buttonGroup1.add(maleRadioButton);
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");

        buttonGroup1.add(femaleRadioButton);
        femaleRadioButton.setText("Female");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cityField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(addressField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(contactNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(nicField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(districtComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(provinceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supplierNoField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nicField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contactNoField)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressField)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cityField)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(districtComboBox)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(provinceComboBox)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Suppliers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "NIC", "Email", "Contact No", "Address", "City", "District", "Province", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierTable.setRowHeight(25);
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);
        if (supplierTable.getColumnModel().getColumnCount() > 0) {
            supplierTable.getColumnModel().getColumn(0).setMinWidth(60);
            supplierTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            supplierTable.getColumnModel().getColumn(1).setMinWidth(150);
            supplierTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            supplierTable.getColumnModel().getColumn(2).setMinWidth(120);
            supplierTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            supplierTable.getColumnModel().getColumn(3).setMinWidth(160);
            supplierTable.getColumnModel().getColumn(3).setPreferredWidth(160);
            supplierTable.getColumnModel().getColumn(4).setMinWidth(100);
            supplierTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            supplierTable.getColumnModel().getColumn(5).setMinWidth(200);
            supplierTable.getColumnModel().getColumn(5).setPreferredWidth(200);
            supplierTable.getColumnModel().getColumn(6).setMinWidth(110);
            supplierTable.getColumnModel().getColumn(6).setPreferredWidth(110);
            supplierTable.getColumnModel().getColumn(7).setMinWidth(110);
            supplierTable.getColumnModel().getColumn(7).setPreferredWidth(110);
            supplierTable.getColumnModel().getColumn(8).setMinWidth(110);
            supplierTable.getColumnModel().getColumn(8).setPreferredWidth(110);
            supplierTable.getColumnModel().getColumn(9).setMinWidth(60);
            supplierTable.getColumnModel().getColumn(9).setPreferredWidth(60);
        }

        keywordField.setForeground(new java.awt.Color(153, 153, 153));
        keywordField.setText("Search");
        keywordField.setToolTipText("Search");
        keywordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                keywordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                keywordFieldFocusLost(evt);
            }
        });
        keywordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Supplier Details", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        logger.debug("Register supplier");
        String supplierNo = supplierNoField.getText();
        String name = nameField.getText();
        String nic = nicField.getText();
        String email = emailField.getText();
        String contactNo = contactNoField.getText();
        String address = addressField.getText();
        String city = cityField.getText();
        int distictNo = districtComboBox.getSelectedIndex() + 1;
        int provinceNo = provinceComboBox.getSelectedIndex() + 1;
        String gender = null;

        if (maleRadioButton.isSelected()) {
            gender = "Male";
        } else if (femaleRadioButton.isSelected()) {
            gender = "Female";
        }

        logger.debug("Check validations");
        if (name.equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Please Enter The Name !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            nameField.requestFocus(true);
            logger.error("Supplier Name not entered");
        } else if (contactNo.equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Please Enter The Contact No !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            contactNoField.requestFocus(true);
            logger.error("Contact No not entered");
        } else if (city.equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Please Enter The City !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            cityField.requestFocus(true);
            logger.error("City not entered");
        } else if (email.length() > 0) {
            String PATTERN = "^[a-zA-Z0-9./]{0,50}[@][a-zA-Z]{0,10}[.][a-zA-Z]{0,5}$";
            Pattern p = Pattern.compile(PATTERN);
            Matcher m = p.matcher(email);
            if (!m.matches()) {
                JOptionPane.showConfirmDialog(rootPane, "Email is Wrong !", "Error", -1, JOptionPane.ERROR_MESSAGE);
                emailField.requestFocus(true);
                logger.error("Email pattern not matched");
            } else {
                String result = supplierModel.registerSupplier(supplierNo, name, nic, email, contactNo, address, city, distictNo, provinceNo, gender);
                if (result.equals("Register Successful")) {
                    JOptionPane.showConfirmDialog(rootPane, result, "Message", -1, 1);
                    clearFields();
                    loadSupplierTable("");
                    logger.debug("Message: " + result);
                } else {
                    JOptionPane.showConfirmDialog(rootPane, result, "Error", -1, JOptionPane.ERROR_MESSAGE);
                    logger.error("Error: " + result);
                }
            }
        } else {
            String result = supplierModel.registerSupplier(supplierNo, name, nic, email, contactNo, address, city, distictNo, provinceNo, gender);
            if (result.equals("Register Successful")) {
                JOptionPane.showConfirmDialog(rootPane, result, "Message", -1, 1);
                clearFields();
                loadSupplierTable("");
                logger.debug("Message: " + result);
            } else {
                JOptionPane.showConfirmDialog(rootPane, result, "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: " + result);
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        logger.debug("Update supplier");
        String supplierNo = supplierNoField.getText();
        String name = nameField.getText();
        String nic = nicField.getText();
        String email = emailField.getText();
        String contactNo = contactNoField.getText();
        String address = addressField.getText();
        String city = cityField.getText();
        int distictNo = districtComboBox.getSelectedIndex() + 1;
        int provinceNo = provinceComboBox.getSelectedIndex() + 1;
        String gender = null;

        if (maleRadioButton.isSelected()) {
            gender = "Male";
        } else if (femaleRadioButton.isSelected()) {
            gender = "Female";
        }

        logger.debug("Check validations");
        if (name.equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Please Enter The Name !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            nameField.requestFocus(true);
            logger.error("Supplier Name not entered");
        } else if (contactNo.equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Please Enter The Contact No !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            contactNoField.requestFocus(true);
            logger.error("Contact No not entered");
        } else if (city.equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Please Enter The City !", "Error", -1, JOptionPane.ERROR_MESSAGE);
            cityField.requestFocus(true);
            logger.error("City not entered");
        } else if (email.length() > 0) {
            String PATTERN = "^[a-zA-Z0-9./]{0,50}[@][a-zA-Z]{0,10}[.][a-zA-Z]{0,5}$";
            Pattern p = Pattern.compile(PATTERN);
            Matcher m = p.matcher(email);
            if (!m.matches()) {
                JOptionPane.showConfirmDialog(rootPane, "Email is Wrong !", "Error", -1, JOptionPane.ERROR_MESSAGE);
                emailField.requestFocus(true);
                logger.error("Email pattern wrong");
            } else {
                String result = supplierModel.updateSupplier(supplierNo, name, nic, email, contactNo, address, city, distictNo, provinceNo, gender);
                if (result.equals("Update Successful")) {
                    JOptionPane.showConfirmDialog(rootPane, result, "Message", -1, 1);
                    loadSupplierTable("");
                    logger.debug("Message: " + result);
                } else {
                    JOptionPane.showConfirmDialog(rootPane, result, "Error", -1, JOptionPane.ERROR_MESSAGE);
                    logger.error("Error: " + result);
                }
            }
        } else {
            String result = supplierModel.updateSupplier(supplierNo, name, nic, email, contactNo, address, city, distictNo, provinceNo, gender);
            if (result.equals("Update Successful")) {
                JOptionPane.showConfirmDialog(rootPane, result, "Message", -1, 1);
                loadSupplierTable("");
                logger.debug("Message: " + result);
            } else {
                JOptionPane.showConfirmDialog(rootPane, result, "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: " + result);
            }
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        logger.debug("Remove supplier");
        String supplierNo = supplierNoField.getText();

        int response = JOptionPane.showConfirmDialog(this, "Do You Want To Remove ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            String result = supplierModel.removeSupplier(supplierNo);
            if (result.equals("Remove Successful")) {
                JOptionPane.showConfirmDialog(rootPane, result, "Message", -1, 1);
                clearFields();
                loadSupplierTable("");
                logger.debug("Message: " + result);
            } else {
                JOptionPane.showConfirmDialog(rootPane, result, "Error", -1, JOptionPane.ERROR_MESSAGE);
                logger.error("Error: " + result);
            }
        }

    }//GEN-LAST:event_removeButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_newButtonActionPerformed

    private void supplierNoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNoFieldKeyPressed
        // TODO add your handling code here:
        supplierNoField.setEditable(false);
    }//GEN-LAST:event_supplierNoFieldKeyPressed

    private void supplierNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNoFieldKeyReleased
        // TODO add your handling code here:
        supplierNoField.setEditable(true);
    }//GEN-LAST:event_supplierNoFieldKeyReleased

    private void contactNoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoFieldKeyPressed
        // TODO add your handling code here:
        String contactNo = contactNoField.getText();
        int length = contactNo.length();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 10) {
                contactNoField.setEditable(true);
            } else {
                contactNoField.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                contactNoField.setEditable(true);
            } else {
                contactNoField.setEditable(false);
            }
        }
    }//GEN-LAST:event_contactNoFieldKeyPressed

    private void contactNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNoFieldKeyReleased
        // TODO add your handling code here:
        contactNoField.setEditable(true);
    }//GEN-LAST:event_contactNoFieldKeyReleased

    private void keywordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFocusGained
        // TODO add your handling code here:
        if (keywordField.getText().equals("Search")) {
            keywordField.setText("");
            keywordField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_keywordFieldFocusGained

    private void keywordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keywordFieldFocusLost
        // TODO add your handling code here:
        if (keywordField.getText().equals("")) {
            keywordField.setText("Search");
            keywordField.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_keywordFieldFocusLost

    private void keywordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordFieldKeyReleased
        // TODO add your handling code here:
        String keyword = keywordField.getText();
        logger.debug("Search supplier data");
        loadSupplierTable(keyword);
    }//GEN-LAST:event_keywordFieldKeyReleased

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        // TODO add your handling code here:
        clearFields();

        int row = supplierTable.getSelectedRow();
        int supplierNo = (int) supplierTableModel.getValueAt(row, 0);
        Object[] supplierData = supplierModel.getSelectedSupplierData(supplierNo);

        supplierNoField.setText(new String(supplierData[0] + ""));
        nameField.setText((String) supplierData[1]);
        nicField.setText((String) supplierData[2]);
        emailField.setText((String) supplierData[3]);
        contactNoField.setText((String) supplierData[4]);
        addressField.setText((String) supplierData[5]);
        cityField.setText((String) supplierData[6]);
        districtComboBox.setSelectedIndex((int) supplierData[7] - 1);
        provinceComboBox.setSelectedIndex((int) supplierData[8] - 1);
        String gender = (String) supplierData[9];

        if (gender.equals("Male")) {
            maleRadioButton.setSelected(true);
        } else if (gender.equals("Female")) {
            femaleRadioButton.setSelected(true);
        }
        logger.debug("Load selected row data to relevant fields");

        registerButton.setEnabled(false);
        updateButton.setEnabled(true);
        removeButton.setEnabled(true);

    }//GEN-LAST:event_supplierTableMouseClicked

    private void supplierNoLoad() {
        int supplierNo = supplierModel.getSupplierNo();
        supplierNo++;
        supplierNoField.setText(new String(supplierNo + ""));
        logger.debug("Set Supplier No");
    }
    
    private void loadSupplierTable(String keyword) {
        supplierModel.loadSupplierTable(keyword, supplierTableModel);
        logger.debug("Load supplier table");
    }

    private void clearFields() {
        supplierNoLoad();
        nameField.setText("");
        nicField.setText("");
        emailField.setText("");
        contactNoField.setText("");
        addressField.setText("");
        cityField.setText("");
        districtComboBox.setSelectedIndex(0);
        provinceComboBox.setSelectedIndex(0);
        maleRadioButton.setSelected(true);

        registerButton.setEnabled(true);
        updateButton.setEnabled(false);
        removeButton.setEnabled(false);

        logger.debug("Clear fields");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SupplierManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SupplierManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SupplierManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SupplierManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField contactNoField;
    private javax.swing.JComboBox<String> districtComboBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keywordField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField nicField;
    private javax.swing.JComboBox<String> provinceComboBox;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField supplierNoField;
    private javax.swing.JTable supplierTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
